# Команды:
# /filench reload - Перезагрузка конфигурации | permission - filench.admin

# Плагин создан LuckStudio

messages:
  reload: "Конфигурация успешна перезагружена!"
  console: "Данная команды должна быть использована игроком!"
  no-item: "Вы не можете переложить данный предмет в эндер сундук!"

items: # Список запрещенных предметов
  - DIAMOND